// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";

export class State {
    "status": string;
    "positionMs": number;
    "volume": number;
    "currentTrack"?: library$0.TrackSummary | null;
    "currentIndex": number;
    "queueLength": number;
    "durationMs"?: number | null;
    "updatedAt": string;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("positionMs" in $$source)) {
            this["positionMs"] = 0;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("currentIndex" in $$source)) {
            this["currentIndex"] = 0;
        }
        if (!("queueLength" in $$source)) {
            this["queueLength"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("currentTrack" in $$parsedSource) {
            $$parsedSource["currentTrack"] = $$createField3_0($$parsedSource["currentTrack"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

// Private type creation functions
const $$createType0 = library$0.TrackSummary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
