// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ExtractOptions {
    "maxDimension": number;
    "quality": number;
    "colorCount": number;
    "candidateCount": number;
    "quantizationBits": number;
    "alphaThreshold": number;
    "ignoreNearWhite": boolean;
    "ignoreNearBlack": boolean;
    "minLuma": number;
    "maxLuma": number;
    "minChroma": number;
    "targetChroma": number;
    "maxChroma": number;
    "minDelta": number;
    "darkBaseLightness": number;
    "lightBaseLightness": number;
    "darkLightnessDeviation": number;
    "lightLightnessDeviation": number;
    "darkChromaScale": number;
    "lightChromaScale": number;
    "workerCount": number;

    /** Creates a new ExtractOptions instance. */
    constructor($$source: Partial<ExtractOptions> = {}) {
        if (!("maxDimension" in $$source)) {
            this["maxDimension"] = 0;
        }
        if (!("quality" in $$source)) {
            this["quality"] = 0;
        }
        if (!("colorCount" in $$source)) {
            this["colorCount"] = 0;
        }
        if (!("candidateCount" in $$source)) {
            this["candidateCount"] = 0;
        }
        if (!("quantizationBits" in $$source)) {
            this["quantizationBits"] = 0;
        }
        if (!("alphaThreshold" in $$source)) {
            this["alphaThreshold"] = 0;
        }
        if (!("ignoreNearWhite" in $$source)) {
            this["ignoreNearWhite"] = false;
        }
        if (!("ignoreNearBlack" in $$source)) {
            this["ignoreNearBlack"] = false;
        }
        if (!("minLuma" in $$source)) {
            this["minLuma"] = 0;
        }
        if (!("maxLuma" in $$source)) {
            this["maxLuma"] = 0;
        }
        if (!("minChroma" in $$source)) {
            this["minChroma"] = 0;
        }
        if (!("targetChroma" in $$source)) {
            this["targetChroma"] = 0;
        }
        if (!("maxChroma" in $$source)) {
            this["maxChroma"] = 0;
        }
        if (!("minDelta" in $$source)) {
            this["minDelta"] = 0;
        }
        if (!("darkBaseLightness" in $$source)) {
            this["darkBaseLightness"] = 0;
        }
        if (!("lightBaseLightness" in $$source)) {
            this["lightBaseLightness"] = 0;
        }
        if (!("darkLightnessDeviation" in $$source)) {
            this["darkLightnessDeviation"] = 0;
        }
        if (!("lightLightnessDeviation" in $$source)) {
            this["lightLightnessDeviation"] = 0;
        }
        if (!("darkChromaScale" in $$source)) {
            this["darkChromaScale"] = 0;
        }
        if (!("lightChromaScale" in $$source)) {
            this["lightChromaScale"] = 0;
        }
        if (!("workerCount" in $$source)) {
            this["workerCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtractOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtractOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtractOptions($$parsedSource as Partial<ExtractOptions>);
    }
}

export class PaletteColor {
    "hex": string;
    "r": number;
    "g": number;
    "b": number;
    "population": number;
    "lightness": number;
    "chroma": number;
    "hue": number;

    /** Creates a new PaletteColor instance. */
    constructor($$source: Partial<PaletteColor> = {}) {
        if (!("hex" in $$source)) {
            this["hex"] = "";
        }
        if (!("r" in $$source)) {
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            this["b"] = 0;
        }
        if (!("population" in $$source)) {
            this["population"] = 0;
        }
        if (!("lightness" in $$source)) {
            this["lightness"] = 0;
        }
        if (!("chroma" in $$source)) {
            this["chroma"] = 0;
        }
        if (!("hue" in $$source)) {
            this["hue"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaletteColor instance from a string or object.
     */
    static createFrom($$source: any = {}): PaletteColor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaletteColor($$parsedSource as Partial<PaletteColor>);
    }
}

export class ThemePalette {
    "primary"?: PaletteColor | null;
    "secondary"?: PaletteColor | null;
    "tertiary"?: PaletteColor | null;
    "dark"?: PaletteColor | null;
    "light"?: PaletteColor | null;
    "accent"?: PaletteColor | null;
    "gradient": PaletteColor[];
    "sourceWidth": number;
    "sourceHeight": number;
    "sampleWidth": number;
    "sampleHeight": number;
    "options": ExtractOptions;

    /** Creates a new ThemePalette instance. */
    constructor($$source: Partial<ThemePalette> = {}) {
        if (!("gradient" in $$source)) {
            this["gradient"] = [];
        }
        if (!("sourceWidth" in $$source)) {
            this["sourceWidth"] = 0;
        }
        if (!("sourceHeight" in $$source)) {
            this["sourceHeight"] = 0;
        }
        if (!("sampleWidth" in $$source)) {
            this["sampleWidth"] = 0;
        }
        if (!("sampleHeight" in $$source)) {
            this["sampleHeight"] = 0;
        }
        if (!("options" in $$source)) {
            this["options"] = (new ExtractOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemePalette instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemePalette {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primary" in $$parsedSource) {
            $$parsedSource["primary"] = $$createField0_0($$parsedSource["primary"]);
        }
        if ("secondary" in $$parsedSource) {
            $$parsedSource["secondary"] = $$createField1_0($$parsedSource["secondary"]);
        }
        if ("tertiary" in $$parsedSource) {
            $$parsedSource["tertiary"] = $$createField2_0($$parsedSource["tertiary"]);
        }
        if ("dark" in $$parsedSource) {
            $$parsedSource["dark"] = $$createField3_0($$parsedSource["dark"]);
        }
        if ("light" in $$parsedSource) {
            $$parsedSource["light"] = $$createField4_0($$parsedSource["light"]);
        }
        if ("accent" in $$parsedSource) {
            $$parsedSource["accent"] = $$createField5_0($$parsedSource["accent"]);
        }
        if ("gradient" in $$parsedSource) {
            $$parsedSource["gradient"] = $$createField6_0($$parsedSource["gradient"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField11_0($$parsedSource["options"]);
        }
        return new ThemePalette($$parsedSource as Partial<ThemePalette>);
    }
}

// Private type creation functions
const $$createType0 = PaletteColor.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = ExtractOptions.createFrom;
