// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "./internal/library/models.js";

export function ListAlbums(): $CancellablePromise<library$0.AlbumSummary[]> {
    return $Call.ByID(1263870718).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListArtists(): $CancellablePromise<library$0.ArtistSummary[]> {
    return $Call.ByID(1280729162).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListTracks(): $CancellablePromise<library$0.TrackSummary[]> {
    return $Call.ByID(1495798414).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = library$0.AlbumSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = library$0.ArtistSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = library$0.TrackSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
