// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "./internal/library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as player$0 from "./internal/player/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as queue$0 from "./internal/queue/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scanner$0 from "./internal/scanner/models.js";

export class StartupSnapshot {
    "queueState": queue$0.State;
    "playerState": player$0.State;
    "scanStatus": scanner$0.Status;
    "albumsPage": library$0.AlbumsPage;
    "themeModePreference": string;

    /** Creates a new StartupSnapshot instance. */
    constructor($$source: Partial<StartupSnapshot> = {}) {
        if (!("queueState" in $$source)) {
            this["queueState"] = (new queue$0.State());
        }
        if (!("playerState" in $$source)) {
            this["playerState"] = (new player$0.State());
        }
        if (!("scanStatus" in $$source)) {
            this["scanStatus"] = (new scanner$0.Status());
        }
        if (!("albumsPage" in $$source)) {
            this["albumsPage"] = (new library$0.AlbumsPage());
        }
        if (!("themeModePreference" in $$source)) {
            this["themeModePreference"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): StartupSnapshot {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("queueState" in $$parsedSource) {
            $$parsedSource["queueState"] = $$createField0_0($$parsedSource["queueState"]);
        }
        if ("playerState" in $$parsedSource) {
            $$parsedSource["playerState"] = $$createField1_0($$parsedSource["playerState"]);
        }
        if ("scanStatus" in $$parsedSource) {
            $$parsedSource["scanStatus"] = $$createField2_0($$parsedSource["scanStatus"]);
        }
        if ("albumsPage" in $$parsedSource) {
            $$parsedSource["albumsPage"] = $$createField3_0($$parsedSource["albumsPage"]);
        }
        return new StartupSnapshot($$parsedSource as Partial<StartupSnapshot>);
    }
}

// Private type creation functions
const $$createType0 = queue$0.State.createFrom;
const $$createType1 = player$0.State.createFrom;
const $$createType2 = scanner$0.Status.createFrom;
const $$createType3 = library$0.AlbumsPage.createFrom;
