// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as player$0 from "./internal/player/models.js";

export function GetState(): $CancellablePromise<player$0.State> {
    return $Call.ByID(2798124289).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Next(): $CancellablePromise<player$0.State> {
    return $Call.ByID(1009561457).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Pause(): $CancellablePromise<player$0.State> {
    return $Call.ByID(191671602).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Play(): $CancellablePromise<player$0.State> {
    return $Call.ByID(1808111650).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Previous(): $CancellablePromise<player$0.State> {
    return $Call.ByID(2487521925).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Seek(positionMS: number): $CancellablePromise<player$0.State> {
    return $Call.ByID(1479346536, positionMS).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetVolume(volume: number): $CancellablePromise<player$0.State> {
    return $Call.ByID(671101282, volume).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Stop(): $CancellablePromise<player$0.State> {
    return $Call.ByID(2311398648).then(($result: any) => {
        return $$createType0($result);
    });
}

export function TogglePlayback(): $CancellablePromise<player$0.State> {
    return $Call.ByID(427686917).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = player$0.State.createFrom;
