// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as queue$0 from "./internal/queue/models.js";

export function AppendTracks(trackIDs: number[]): $CancellablePromise<queue$0.State> {
    return $Call.ByID(1039070430, trackIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Clear(): $CancellablePromise<queue$0.State> {
    return $Call.ByID(3867432031).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetState(): $CancellablePromise<queue$0.State> {
    return $Call.ByID(1595367599).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemoveTrack(index: number): $CancellablePromise<queue$0.State> {
    return $Call.ByID(3456322137, index).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetCurrentIndex(index: number): $CancellablePromise<queue$0.State> {
    return $Call.ByID(1250430805, index).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetQueue(trackIDs: number[], startIndex: number): $CancellablePromise<queue$0.State> {
    return $Call.ByID(2750140625, trackIDs, startIndex).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = queue$0.State.createFrom;
