// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scanner$0 from "./internal/scanner/models.js";

export function GetStatus(): $CancellablePromise<scanner$0.Status> {
    return $Call.ByID(966301467).then(($result: any) => {
        return $$createType0($result);
    });
}

export function TriggerFullScan(): $CancellablePromise<void> {
    return $Call.ByID(1583516401);
}

export function TriggerIncrementalScan(): $CancellablePromise<void> {
    return $Call.ByID(4128331878);
}

export function TriggerScan(): $CancellablePromise<void> {
    return $Call.ByID(1754448716);
}

// Private type creation functions
const $$createType0 = scanner$0.Status.createFrom;
