// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "./internal/library/models.js";

export function AddWatchedRoot(path: string): $CancellablePromise<library$0.WatchedRoot> {
    return $Call.ByID(345313763, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListWatchedRoots(): $CancellablePromise<library$0.WatchedRoot[]> {
    return $Call.ByID(687846755).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoveWatchedRoot(id: number): $CancellablePromise<void> {
    return $Call.ByID(4081202698, id);
}

export function SetWatchedRootEnabled(id: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(583001791, id, enabled);
}

// Private type creation functions
const $$createType0 = library$0.WatchedRoot.createFrom;
const $$createType1 = $Create.Array($$createType0);
