// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stats$0 from "./internal/stats/models.js";

export function GetDashboard(rangeKey: string, limit: number): $CancellablePromise<stats$0.Dashboard> {
    return $Call.ByID(1674425190, rangeKey, limit).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetOverview(limit: number): $CancellablePromise<stats$0.Overview> {
    return $Call.ByID(191675605, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = stats$0.Dashboard.createFrom;
const $$createType1 = stats$0.Overview.createFrom;
