// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as palette$0 from "./internal/palette/models.js";

export function DefaultOptions(): $CancellablePromise<palette$0.ExtractOptions> {
    return $Call.ByID(756867029).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GenerateFromCover(coverPath: string, options: palette$0.ExtractOptions): $CancellablePromise<palette$0.ThemePalette> {
    return $Call.ByID(3858850, coverPath, options).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = palette$0.ExtractOptions.createFrom;
const $$createType1 = palette$0.ThemePalette.createFrom;
