// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Progress {
    "phase": string;
    "message": string;
    "percent": number;
    "status": string;
    "at": string;

    /** Creates a new Progress instance. */
    constructor($$source: Partial<Progress> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Progress instance from a string or object.
     */
    static createFrom($$source: any = {}): Progress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Progress($$parsedSource as Partial<Progress>);
    }
}

export class Status {
    "running": boolean;
    "lastRunAt": string;
    "lastError"?: string;
    "lastFilesSeen": number;
    "lastIndexed": number;
    "lastSkipped": number;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("lastRunAt" in $$source)) {
            this["lastRunAt"] = "";
        }
        if (!("lastFilesSeen" in $$source)) {
            this["lastFilesSeen"] = 0;
        }
        if (!("lastIndexed" in $$source)) {
            this["lastIndexed"] = 0;
        }
        if (!("lastSkipped" in $$source)) {
            this["lastSkipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
