// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ArtistStat {
    "name": string;
    "playedMs": number;
    "trackCount": number;

    /** Creates a new ArtistStat instance. */
    constructor($$source: Partial<ArtistStat> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("playedMs" in $$source)) {
            this["playedMs"] = 0;
        }
        if (!("trackCount" in $$source)) {
            this["trackCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtistStat instance from a string or object.
     */
    static createFrom($$source: any = {}): ArtistStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtistStat($$parsedSource as Partial<ArtistStat>);
    }
}

export class Overview {
    "totalPlayedMs": number;
    "tracksPlayed": number;
    "completeCount": number;
    "skipCount": number;
    "partialCount": number;
    "topTracks": TrackStat[];
    "topArtists": ArtistStat[];

    /** Creates a new Overview instance. */
    constructor($$source: Partial<Overview> = {}) {
        if (!("totalPlayedMs" in $$source)) {
            this["totalPlayedMs"] = 0;
        }
        if (!("tracksPlayed" in $$source)) {
            this["tracksPlayed"] = 0;
        }
        if (!("completeCount" in $$source)) {
            this["completeCount"] = 0;
        }
        if (!("skipCount" in $$source)) {
            this["skipCount"] = 0;
        }
        if (!("partialCount" in $$source)) {
            this["partialCount"] = 0;
        }
        if (!("topTracks" in $$source)) {
            this["topTracks"] = [];
        }
        if (!("topArtists" in $$source)) {
            this["topArtists"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     */
    static createFrom($$source: any = {}): Overview {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("topTracks" in $$parsedSource) {
            $$parsedSource["topTracks"] = $$createField5_0($$parsedSource["topTracks"]);
        }
        if ("topArtists" in $$parsedSource) {
            $$parsedSource["topArtists"] = $$createField6_0($$parsedSource["topArtists"]);
        }
        return new Overview($$parsedSource as Partial<Overview>);
    }
}

export class TrackStat {
    "trackId": number;
    "title": string;
    "artist": string;
    "album": string;
    "coverPath"?: string | null;
    "playedMs": number;
    "completeCount": number;
    "skipCount": number;
    "partialCount": number;

    /** Creates a new TrackStat instance. */
    constructor($$source: Partial<TrackStat> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("playedMs" in $$source)) {
            this["playedMs"] = 0;
        }
        if (!("completeCount" in $$source)) {
            this["completeCount"] = 0;
        }
        if (!("skipCount" in $$source)) {
            this["skipCount"] = 0;
        }
        if (!("partialCount" in $$source)) {
            this["partialCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackStat instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackStat($$parsedSource as Partial<TrackStat>);
    }
}

// Private type creation functions
const $$createType0 = TrackStat.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ArtistStat.createFrom;
const $$createType3 = $Create.Array($$createType2);
