// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";

export class State {
    "entries": library$0.TrackSummary[];
    "currentIndex": number;
    "currentTrack"?: library$0.TrackSummary | null;
    "total": number;
    "updatedAt": string;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("currentIndex" in $$source)) {
            this["currentIndex"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        if ("currentTrack" in $$parsedSource) {
            $$parsedSource["currentTrack"] = $$createField2_0($$parsedSource["currentTrack"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

// Private type creation functions
const $$createType0 = library$0.TrackSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
